#!/bin/sh

# This file runs when a DM logs you into a graphical session.
# If you use startx/xinit like a Chad, this file will also be sourced.

#setxkbmap "us_intl,ru" "altgr-intl,"        # Add russian layout to keyboard
#xbindkeys -f "$XDG_CONFIG_HOME"/xbindkeys/config
#claws-mail --alternate-config-dir "$XDG_DATA_HOME"/claws-mail &
xrandr --dpi 96		# Set DPI. User may want to use a larger number for larger screens.
autorandr --change
xset r rate 300 50      # Speed xrate up

setbg &			# set the background with the `setbg` script
xrdb ${XDG_CONFIG_HOME:-$HOME/.config}/x11/xresources & xrdbpid=$!	# Uncomment to use Xresources colors/settings on startup

# Ensure that xrdb has finished running before moving on to start the WM/DE.
[ -n "$xrdbpid" ] && wait "$xrdbpid"

#autostart="mpd xcompmgr dunst unclutter pipewire nm-applet"
autostart="redshift dunst unclutter picom transmission-daemon dwmblocks"

for program in $autostart; do
	pidof -s "$program" || setsid -f "$program"
done >/dev/null 2>&1
