#!/bin/sh

# This file runs when a DM logs you into a graphical session.
# If you use startx/xinit like a Chad, this file will also be sourced.

#setxkbmap "us_intl,ru" "altgr-intl,"        # Add russian layout to keyboard
#setxkbmap "us_intl,ru" "altgr-intl," -option 'grp:alt_shift_toggle'
#xbindkeys -f "$XDG_CONFIG_HOME"/xbindkeys/config
#claws-mail --alternate-config-dir "$XDG_DATA_HOME"/claws-mail &
xrandr --dpi 96		# Set DPI. User may want to use a larger number for larger screens.
autorandr --change
xset r rate 300 50      # Speed xrate up

setbg &			# set the background with the `setbg` script
xrdb ${XDG_CONFIG_HOME:-$HOME/.config}/x11/xresources & xrdbpid=$!	# Uncomment to use Xresources colors/settings on startup

#systemctl --user enable pipewire
#autostart="mpd xcompmgr dunst unclutter pipewire nm-applet"
autostart="dunst mpd unclutter picom transmission-daemon dwmblocks redshift"

for program in $autostart; do
	#pidof -s "$program" || setsid -f "$program"
	pidof -s "$program" || "$program" &
done >/dev/null 2>&1

# Fix to update audio module, else module displays the wrong volume
$(sleep 2s && pkill -RTMIN+2 dwmblocks) &

# Ensure that xrdb has finished running before moving on to start the WM/DE.
[ -n "$xrdbpid" ] && wait "$xrdbpid"
